app/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using app.Models;

namespace app.Controllers
{
    public class DataController : Controller
    {
        private readonly dataContext _context;

        public DataController(dataContext context)
        {
            _context = context;
        }

        // GET: Data
        public async Task<IActionResult> Index(string searchString)
        {
            var personer = from p in _context.Personer
                         select p;

            if (!String.IsNullOrEmpty(searchString))
            {
                personer = personer.Where(s => s.Fornavn.Contains(searchString));
            }
            return View(await personer.ToListAsync());
        }

        // GET: Data/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personer = await _context.Personer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (personer == null)
            {
                return NotFound();
            }

            return View(personer);
        }

        // GET: Data/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Data/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fornavn,Efternavn,Adresse,Adresse2,Postnr,By,Telefonnr")] Personer personer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(personer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(personer);
        }

        // GET: Data/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personer = await _context.Personer.FindAsync(id);
            if (personer == null)
            {
                return NotFound();
            }
            return View(personer);
        }

        // POST: Data/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Fornavn,Efternavn,Adresse,Adresse2,Postnr,By,Telefonnr")] Personer personer)
        {
            if (id != personer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(personer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonerExists(personer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(personer);
        }

        // GET: Data/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var personer = await _context.Personer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (personer == null)
            {
                return NotFound();
            }

            return View(personer);
        }

        // POST: Data/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var personer = await _context.Personer.FindAsync(id);
            _context.Personer.Remove(personer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonerExists(long id)
        {
            return _context.Personer.Any(e => e.Id == id);
        }
    }
}

app/Views/Data/Create.cshtml
@model app.Models.Personer

@{ ViewData["Title"] = "Create"; }

<h1>Create</h1>

<h4>Personer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fornavn" class="control-label"></label>
                <input asp-for="Fornavn" class="form-control" />
                <span asp-validation-for="Fornavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Efternavn" class="control-label"></label>
                <input asp-for="Efternavn" class="form-control" />
                <span asp-validation-for="Efternavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse2" class="control-label"></label>
                <input asp-for="Adresse2" class="form-control" />
                <span asp-validation-for="Adresse2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Postnr" class="control-label"></label>
                <input asp-for="Postnr" class="form-control" />
                <span asp-validation-for="Postnr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="By" class="control-label"></label>
                <input asp-for="By" class="form-control" />
                <span asp-validation-for="By" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefonnr" class="control-label"></label>
                <input asp-for="Telefonnr" class="form-control" />
                <span asp-validation-for="Telefonnr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

app/Views/Data/Delete.cshtml
@model app.Models.Personer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Personer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fornavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fornavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Efternavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Efternavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Postnr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Postnr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.By)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.By)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefonnr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefonnr)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

app/Views/Data/Details.cshtml
@model app.Models.Personer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Personer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fornavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fornavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Efternavn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Efternavn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adresse2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Postnr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Postnr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.By)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.By)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefonnr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefonnr)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

app/Views/Data/Edit.cshtml
@model app.Models.Personer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Personer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Fornavn" class="control-label"></label>
                <input asp-for="Fornavn" class="form-control" />
                <span asp-validation-for="Fornavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Efternavn" class="control-label"></label>
                <input asp-for="Efternavn" class="form-control" />
                <span asp-validation-for="Efternavn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse2" class="control-label"></label>
                <input asp-for="Adresse2" class="form-control" />
                <span asp-validation-for="Adresse2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Postnr" class="control-label"></label>
                <input asp-for="Postnr" class="form-control" />
                <span asp-validation-for="Postnr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="By" class="control-label"></label>
                <input asp-for="By" class="form-control" />
                <span asp-validation-for="By" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefonnr" class="control-label"></label>
                <input asp-for="Telefonnr" class="form-control" />
                <span asp-validation-for="Telefonnr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

app/Views/Data/Index.cshtml
@model IEnumerable<app.Models.Personer>

@{ ViewData["Title"] = "Index"; }

<h1>Index</h1>

<p>
    <a asp-action="Create">Tilføj person</a>
</p>
<form asp-controller="Data" asp-action="Index" method="get">
    <p>
        Søg på fornavn: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fornavn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Efternavn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adresse)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adresse2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Postnr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.By)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefonnr)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Fornavn)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Efternavn)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Adresse)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Adresse2)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Postnr)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.By)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Telefonnr)
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
    </td>
</tr>}
    </tbody>
</table>